#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcbuffer.h>
#include <wx/dcclient.h>
#include <wx/dcmemory.h>
#include <wx/wx.h>

#include <vector>

#include "GUIMyDialog1.h"

class LoadingDialog : public wxDialog {
   public:
    wxGauge* progressBar;

    LoadingDialog(wxWindow* parent)
        : wxDialog(parent, wxID_ANY, wxString::FromUTF8("Proszę czekać"),
                   wxDefaultPosition, wxDefaultSize,
                   wxCAPTION | wxSTAY_ON_TOP) {
        wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
        wxStaticText* label = new wxStaticText(
            this, wxID_ANY, wxString::FromUTF8("Trwa generowanie obrazów"));
        progressBar = new wxGauge(this, wxID_ANY, 100, wxDefaultPosition,
                                  wxDefaultSize, wxGA_HORIZONTAL);
        progressBar->SetValue(0);

        sizer->Add(label, 0, wxALL | wxALIGN_CENTER, 10);
        sizer->Add(progressBar, 0, wxALL | wxEXPAND, 10);

        SetSizerAndFit(sizer);
        Centre();
    }
};

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1 {
   protected:
    // Handlers for MyFrame1 events.
    void changeSize(wxSizeEvent& event);
    void drawOnPaint(wxPaintEvent& event);
    void scrollChangeAxisNumber(wxScrollEvent& event);
    void scrollRotate(wxScrollEvent& event);
    void translateX(wxScrollEvent& event);
    void translateY(wxScrollEvent& event);
    void drawOnChange(wxCommandEvent& event);
    void drawAxisChange(wxCommandEvent& event);
    void changeInterpolator(wxCommandEvent& event);
    void loadImage(wxCommandEvent& event);
    void clickSaveSeries(wxCommandEvent& event);
    void clickSave(wxCommandEvent& event);
    void clickDraw(wxCommandEvent& event);

   public:
    /** Constructor */
    GUIMyFrame1(wxWindow* parent);
    //// end generated class members
    const wxWindowID id = wxNewId();
    wxImage img, imgCopy, imgResized, imgOriginal;
    bool linear = true, onChange = false, drawAxisBool = true, toResize = true;
    std::vector<double> axisVect;
    int a;
    double angle;
    void Repaint();
    void setAxis(int number);
    void drawAxis();
    void drawKaleidoscope();
    void translateX(double translation);
    void translateY(double translation);
    void resetOptions();
    float cubicInterpolate(float p[4], float x);
    float bicubicInterpolate(float patch[4][4], float x, float y);
    wxImage RotateImageCubic(const wxImage& source, double angleDegrees);
    wxImage RotateImageLinear(const wxImage& source, double angleDegrees);
    wxImage MirrorRightHalf(const wxImage& source);
    void generateSeries(wxString path, Config config);
    LoadingDialog* dlg;
    void OnThreadCompletion(wxCommandEvent& event);
    void UpdateProgressBar(wxCommandEvent& event);
    void onResizeTimer(wxTimerEvent& event);
    const long ID_UPDATE_PROGRESS = wxNewId();
    wxTimer resizeTimer;
    void resizeImages();
};

#endif  // __GUIMyFrame1__
