#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcbuffer.h>
#include <wx/dcclient.h>
#include <wx/dcmemory.h>
#include <wx/wx.h>

#include <filesystem>

#include "GUIMyDialog1.h"
#include "Kaleidoscope.h"
#include "SeriesWorkerThread.h"

class LoadingDialog : public wxDialog {
   public:
    wxGauge* progressBar;

    LoadingDialog(wxWindow* parent)
        : wxDialog(parent, wxID_ANY, wxString::FromUTF8("Proszę czekać"),
                   wxDefaultPosition, wxDefaultSize,
                   wxCAPTION | wxSTAY_ON_TOP) {
        wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
        wxStaticText* label = new wxStaticText(
            this, wxID_ANY, wxString::FromUTF8("Trwa generowanie obrazów"));
        progressBar = new wxGauge(this, wxID_ANY, 100, wxDefaultPosition,
                                  wxDefaultSize, wxGA_HORIZONTAL);
        progressBar->SetValue(0);

        sizer->Add(label, 0, wxALL | wxALIGN_CENTER, 10);
        sizer->Add(progressBar, 0, wxALL | wxEXPAND, 10);

        SetSizerAndFit(sizer);
        Centre();
    }
};

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1 {
   protected:
    // Handlers for MyFrame1 events.
    void changeSize(wxSizeEvent& event);
    void drawOnPaint(wxPaintEvent& event);
    void scrollChangeAxis(wxScrollEvent& event);
    void scrollChangeAngle(wxScrollEvent& event);
    void scrollChangeTranslateX(wxScrollEvent& event);
    void scrollChangeTranslateY(wxScrollEvent& event);
    void choiceChangeInterpolator(wxCommandEvent& event);
    void choiceChangeAutoUpdate(wxCommandEvent& event);
    void choiceChangeDrawAxis(wxCommandEvent& event);
    void clickLoadImage(wxCommandEvent& event);
    void clickSaveSeries(wxCommandEvent& event);
    void clickSave(wxCommandEvent& event);
    void clickDraw(wxCommandEvent& event);

   public:
    /** Constructor */
    GUIMyFrame1(wxWindow* parent);
    //// end generated class members
    Kaleidoscope gen;
    const wxWindowID ID_WINDOW = wxNewId();
    const wxWindowID ID_UPDATE_PROGRESS = wxNewId();
    LoadingDialog* dlg;
    wxTimer resizeTimer;
    bool auto_update = false;
    void resetOptions();
    bool ensureImageLoaded();
    void generateSeries(wxString path, Config config);
};

#endif  // __GUIMyFrame1__
